#!/bin/bash

echo "Running pre-push hook"

echo "validate composer:"
composer validate
if [ $? -ne 0 ]; then
 echo "Composer must be valid before push!"
 exit 1
fi

echo "run code analysis:"
composer lint
if [ $? -ne 0 ]; then
 echo "Code analysis must pass before push!"
 exit 1
fi

echo "run tests:"
composer test
if [ $? -ne 0 ]; then
 echo "Tests must pass before push!"
 exit 1
fi

exit 0